package architecture

import (
	"fmt"
	"os"
	"path"
	"path/filepath"
	"slices"
	"testing"
)

// maxDirectFiles applies separately to production and test files: a directory
// may hold twenty of each.
const maxDirectFiles = 20

// TestProductionFileLimit applies to each directory independently. Generated
// production and inactive build variants count; tests and external trees do not.
// Nested packages have their own allowance, with no migration-debt baseline.
func TestProductionFileLimit(t *testing.T) {
	t.Parallel()
	inventory := newRepositorySourceInventory(t)
	counts := directFileCounts(inventory.layoutGoFiles(t, "."))
	for _, directory := range overLimitDirectories(counts) {
		t.Errorf("%s has %d direct production Go files; maximum is %d", directory, counts[directory], maxDirectFiles)
	}
}

// TestTestFileLimit counts test files separately from production files. Go
// compiles white-box tests only from the package's own directory, so a crowded
// directory is fixed by grouping tests by behavior, not by moving them.
func TestTestFileLimit(t *testing.T) {
	t.Parallel()
	inventory := newRepositorySourceInventory(t)
	counts := directFileCounts(inventory.testLayoutGoFiles(t, "."))
	for _, directory := range overLimitDirectories(counts) {
		t.Errorf("%s has %d direct test Go files; maximum is %d", directory, counts[directory], maxDirectFiles)
	}
}

func directFileCounts(sources []repositoryGoSource) map[string]int {
	counts := make(map[string]int)
	for _, source := range sources {
		counts[path.Dir(source.repositoryPath)]++
	}
	return counts
}

func overLimitDirectories(counts map[string]int) []string {
	var directories []string
	for directory, count := range counts {
		if count > maxDirectFiles {
			directories = append(directories, directory)
		}
	}
	slices.Sort(directories)
	return directories
}

func TestProductionFileLimitBoundaryAndNesting(t *testing.T) {
	t.Parallel()
	for _, test := range []struct {
		name          string
		parent, child int
		want          []string
	}{
		{"twenty", 20, 0, nil},
		{"twenty-one", 21, 0, []string{"engine"}},
		{"independent nested allowance", 20, 20, nil},
		{"nested violation", 20, 21, []string{"engine/proof"}},
	} {
		t.Run(test.name, func(t *testing.T) {
			root := t.TempDir()
			for directory, count := range map[string]int{"engine": test.parent, "engine/proof": test.child} {
				for index := range count {
					writeLayoutSource(t, root, fmt.Sprintf("%s/file%d.go", directory, index), "package engine\n")
				}
			}
			inventory := repositorySourceInventory{root: root}
			counts := directFileCounts(inventory.layoutGoFiles(t, ".", "engine"))
			if got := overLimitDirectories(counts); !slices.Equal(got, test.want) {
				t.Fatalf("violations = %v, want %v; counts = %v", got, test.want, counts)
			}
		})
	}
}

func TestProductionFileLimitCountingScope(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	for index := range 18 {
		writeLayoutSource(t, root, fmt.Sprintf("engine/file%d.go", index), "package engine\n")
	}
	writeLayoutSource(t, root, "engine/generated.go", "// Code generated by fixture. DO NOT EDIT.\npackage engine\n")
	writeLayoutSource(t, root, "engine/variant.go", "//go:build never\n\npackage engine\n")
	for _, name := range []string{
		"engine/generated_test.go", "engine/example_test.go", "engine/testdata/invalid.go",
		"fixtures/invalid.go", "fixture/invalid.go", "vendor/invalid.go", "node_modules/invalid.go",
		".build/checkouts/invalid.go", "_scratch/invalid.go",
	} {
		writeLayoutSource(t, root, name, "not Go source")
	}
	inventory := repositorySourceInventory{root: root}
	counts := directFileCounts(inventory.layoutGoFiles(t, "."))
	if len(counts) != 1 || counts["engine"] != 20 || len(overLimitDirectories(counts)) != 0 {
		t.Fatalf("layout scope counts = %v, want engine:20 only", counts)
	}
	writeLayoutSource(t, root, "engine/generated_second.go", "// Code generated by fixture. DO NOT EDIT.\npackage engine\n")
	if got := overLimitDirectories(directFileCounts(inventory.layoutGoFiles(t, "."))); !slices.Equal(got, []string{"engine"}) {
		t.Fatalf("generated twenty-first file escaped the limit: %v", got)
	}
}

// TestTestFileLimitCountingScope keeps the two allowances independent: twenty
// production files and twenty tests may share a directory, generated tests
// count, and fixture or hidden trees stay out of both views.
func TestTestFileLimitCountingScope(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	for index := range 20 {
		writeLayoutSource(t, root, fmt.Sprintf("engine/file%d.go", index), "package engine\n")
	}
	for index := range 19 {
		writeLayoutSource(t, root, fmt.Sprintf("engine/file%d_test.go", index), "package engine\n")
	}
	writeLayoutSource(t, root, "engine/generated_test.go", "// Code generated by fixture. DO NOT EDIT.\npackage engine\n")
	for _, name := range []string{
		"engine/testdata/invalid_test.go", "fixtures/invalid_test.go", "vendor/invalid_test.go", "_scratch/invalid_test.go",
	} {
		writeLayoutSource(t, root, name, "not Go source")
	}
	inventory := repositorySourceInventory{root: root}
	productionCounts := directFileCounts(inventory.layoutGoFiles(t, "."))
	testCounts := directFileCounts(inventory.testLayoutGoFiles(t, "."))
	if productionCounts["engine"] != 20 || len(testCounts) != 1 || testCounts["engine"] != 20 {
		t.Fatalf("production counts = %v, test counts = %v; want engine:20 in each", productionCounts, testCounts)
	}
	if got := overLimitDirectories(testCounts); len(got) != 0 {
		t.Fatalf("twenty tests beside twenty production files exceeded the limit: %v", got)
	}
	writeLayoutSource(t, root, "engine/extra_test.go", "package engine_test\n")
	if got := overLimitDirectories(directFileCounts(inventory.testLayoutGoFiles(t, "."))); !slices.Equal(got, []string{"engine"}) {
		t.Fatalf("twenty-first test file escaped the limit: %v", got)
	}
}

func writeLayoutSource(t *testing.T, root, name, source string) {
	t.Helper()
	target := filepath.Join(root, filepath.FromSlash(name))
	if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(target, []byte(source), 0o600); err != nil {
		t.Fatal(err)
	}
}
