package architecture

import (
	"os"
	"path/filepath"
	"slices"
	"testing"
)

func TestSourceInventoryExcludesNonProductionTrees(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	files := map[string]string{
		"main.go":                      "package main\n",
		"internal/worker/work.go":      "package worker\n",
		"internal/worker/work_test.go": "not Go source",
		"internal/worker/generated.go": "// Code generated by test. DO NOT EDIT.\npackage worker\n",
	}
	for _, directory := range []string{".build/audit/checkouts/template", ".cache", "_scratch", "fixture", "fixtures", "testdata", "vendor"} {
		files[directory+"/invalid.go"] = "not Go source"
	}
	for name, source := range files {
		path := filepath.Join(root, filepath.FromSlash(name))
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, []byte(source), 0o600); err != nil {
			t.Fatal(err)
		}
	}
	inventory := repositorySourceInventory{root: root}
	var got []string
	for _, source := range inventory.productionGoFiles(t, ".", "internal") {
		got = append(got, source.repositoryPath)
	}
	want := []string{"internal/worker/work.go", "main.go"}
	if !slices.Equal(got, want) {
		t.Fatalf("production source = %v, want %v", got, want)
	}
}

func TestSourceInventoryIncludesAuthoredTests(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	for name, source := range map[string]string{
		"main.go":              "package main\n",
		"main_test.go":         "package main\n",
		"generated_test.go":    "// Code generated by test. DO NOT EDIT.\npackage main\n",
		"testdata/bad_test.go": "not Go source",
	} {
		path := filepath.Join(root, filepath.FromSlash(name))
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, []byte(source), 0o600); err != nil {
			t.Fatal(err)
		}
	}
	inventory := repositorySourceInventory{root: root}
	var got []string
	for _, source := range inventory.authoredGoFiles(t, ".", ".") {
		got = append(got, source.repositoryPath)
	}
	want := []string{"main.go", "main_test.go"}
	if !slices.Equal(got, want) {
		t.Fatalf("authored source = %v, want %v", got, want)
	}
}
