package syntax

import (
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"strconv"
	"testing"

	"golang.org/x/tools/go/analysis"
)

func TestAnalyzeFileDriverSelection(t *testing.T) {
	arguments := os.Args
	t.Cleanup(func() { os.Args = arguments })
	for _, driver := range []struct {
		name      string
		arguments []string
		canonical bool
		tests     bool
		want      bool
	}{
		{"ordinary", []string{"gohawk", "./..."}, false, false, true},
		{"uncanonical test variant", []string{"driver", "./..."}, false, true, false},
		{"canonical test variant", []string{"driver", "./..."}, true, true, true},
		{"vet test variant", []string{"gohawk", "unit.cfg"}, false, true, true},
	} {
		t.Run(driver.name, func(t *testing.T) {
			os.Args = driver.arguments
			files := token.NewFileSet()
			production, err := parser.ParseFile(files, "p.go", "package p\n", parser.ParseComments)
			if err != nil {
				t.Fatal(err)
			}
			generated, err := parser.ParseFile(files, "generated.go", "// Code generated by fixture. DO NOT EDIT.\npackage p\n", parser.ParseComments)
			if err != nil {
				t.Fatal(err)
			}
			pass := &analysis.Pass{Fset: files, Files: []*ast.File{production, generated}}
			if driver.tests {
				test, err := parser.ParseFile(files, "p_test.go", "package p\n", 0)
				if err != nil {
					t.Fatal(err)
				}
				pass.Files = append(pass.Files, test)
				if AnalyzeFile(pass, test) {
					t.Fatal("test files must remain excluded")
				}
			}
			if driver.canonical {
				pass.ResultOf = map[*analysis.Analyzer]any{nil: CanonicalTestVariant{}}
			}
			if AnalyzeFile(pass, production) != driver.want || AnalyzeFile(pass, generated) {
				t.Fatal("driver selection changed production or generated-file policy")
			}
		})
	}
}

func BenchmarkAnalyzeFileVetPackage(b *testing.B) {
	arguments := os.Args
	os.Args = []string{"gohawk", "unit.cfg"}
	b.Cleanup(func() { os.Args = arguments })
	files := token.NewFileSet()
	pass := &analysis.Pass{Fset: files}
	for index := range 200 {
		file, err := parser.ParseFile(files, "p"+strconv.Itoa(index)+".go", "package p\n", 0)
		if err != nil {
			b.Fatal(err)
		}
		pass.Files = append(pass.Files, file)
	}
	b.ReportAllocs()
	for b.Loop() {
		if !AnalyzeFile(pass, pass.Files[0]) {
			b.Fatal("production source rejected by vet driver")
		}
	}
}

func TestSourceRangeRecoversCallFromLeftParenthesis(t *testing.T) {
	files := token.NewFileSet()
	file, err := parser.ParseFile(files, "example.go", "package p\nfunc f() { target(1) }\n", 0)
	if err != nil {
		t.Fatal(err)
	}
	var call *ast.CallExpr
	ast.Inspect(file, func(node ast.Node) bool {
		if typed, ok := node.(*ast.CallExpr); ok {
			call = typed
		}
		return true
	})
	if call == nil {
		t.Fatal("call expression not found")
	}
	rangeAtCall := SourceRange(&analysis.Pass{Fset: files, Files: []*ast.File{file}}, call.Lparen)
	if rangeAtCall.Pos() != call.Pos() || rangeAtCall.End() != call.End() {
		t.Fatalf("range = %v..%v, want %v..%v", rangeAtCall.Pos(), rangeAtCall.End(), call.Pos(), call.End())
	}
}

func TestVetToolInvocation(t *testing.T) {
	for _, test := range []struct {
		name      string
		arguments []string
		want      bool
	}{
		{name: "unitchecker config", arguments: []string{"gohawk", "-json", "/tmp/vet.cfg"}, want: true},
		{name: "standalone packages", arguments: []string{"gohawk", "-json", "./..."}},
	} {
		t.Run(test.name, func(t *testing.T) {
			if got := vetToolInvocation(test.arguments); got != test.want {
				t.Fatalf("vetToolInvocation(%v) = %t, want %t", test.arguments, got, test.want)
			}
		})
	}
}

func TestCanonicalTestVariantResult(t *testing.T) {
	marker := &analysis.Analyzer{Name: "marker", Doc: "test marker", Run: func(*analysis.Pass) (any, error) { return nil, nil }}
	pass := &analysis.Pass{ResultOf: map[*analysis.Analyzer]any{marker: CanonicalTestVariant{}}}
	if !canonicalTestVariant(pass) {
		t.Fatal("canonicalTestVariant did not recognize the typed source-selection result")
	}
	pass.ResultOf[marker] = true
	if canonicalTestVariant(pass) {
		t.Fatal("canonicalTestVariant accepted an unrelated prerequisite result")
	}
}

func TestAnalyzeFileSkipsTestFiles(t *testing.T) {
	files := token.NewFileSet()
	production, err := parser.ParseFile(files, "p.go", "package p\n", 0)
	if err != nil {
		t.Fatal(err)
	}
	test, err := parser.ParseFile(files, "p_test.go", "package p\n", 0)
	if err != nil {
		t.Fatal(err)
	}
	marker := &analysis.Analyzer{Name: "marker", Doc: "test marker", Run: func(*analysis.Pass) (any, error) { return nil, nil }}
	// The augmented test variant is the only pass this driver runs.
	pass := &analysis.Pass{
		Fset: files, Files: []*ast.File{production, test},
		ResultOf: map[*analysis.Analyzer]any{marker: CanonicalTestVariant{}},
	}
	if !AnalyzeFile(pass, production) || AnalyzeFile(pass, test) {
		t.Fatal("analysis must keep production files and skip test files")
	}
}
