package main

// Shared-helper references are generated per package so an agent can load only
// the API it needs. The curated routing guide owns usage policy; declarations
// and their source comments remain authoritative for individual contracts.

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/doc"
	"go/printer"
	"go/token"
	"maps"
	"os"
	"path/filepath"
	"slices"
	"strings"
)

const helperReferenceDirectory = ".agents/skills/gohawk-codebase/references"

func helperPackagePaths(root string) ([]string, error) {
	paths := []string{"internal/syntax", "internal/ssaflow", "internal/summaries", "internal/syncgraph"}
	entries, err := os.ReadDir(filepath.Join(root, "internal/passes"))
	if err != nil {
		return nil, err
	}
	for _, entry := range entries {
		if entry.IsDir() && !strings.HasPrefix(entry.Name(), ".") && !strings.HasPrefix(entry.Name(), "_") && entry.Name() != "testdata" {
			paths = append(paths, "internal/passes/"+entry.Name())
		}
	}
	slices.Sort(paths)
	return paths, nil
}

func generateHelperReferences(root string, updates map[string][]byte) error {
	paths, err := helperPackagePaths(root)
	if err != nil {
		return err
	}
	var links []string
	for _, directory := range paths {
		pkg, err := parsePackageDoc(root, directory)
		if err != nil {
			return err
		}
		page := pkg.Name + ".md"
		body, err := helperReference(root, directory, pkg)
		if err != nil {
			return err
		}
		updates[filepath.Join(root, helperReferenceDirectory, page)] = []byte(body)
		links = append(links, fmt.Sprintf("- [%s](%s)", directory, page))
	}
	path := filepath.Join(root, helperIndexPage)
	contents, err := os.ReadFile(path) // #nosec G304 -- fixed repository-relative routing page
	if err != nil {
		return err
	}
	updated, err := replaceGeneratedBlock(contents, generatedHelpersStart, generatedHelpersEnd, strings.Join(links, "\n"))
	if err != nil {
		return err
	}
	updates[path] = updated
	return nil
}

type helperDeclaration struct {
	name, comment string
	node          ast.Node
}

func helperDeclarations(pkg *doc.Package) []helperDeclaration {
	var declarations []helperDeclaration
	values := func(groups []*doc.Value) {
		for _, group := range groups {
			declarations = append(declarations, helperDeclaration{strings.Join(group.Names, ", "), group.Doc, group.Decl})
		}
	}
	function := func(prefix string, fn *doc.Func) {
		declarations = append(declarations, helperDeclaration{prefix + fn.Name, fn.Doc, fn.Decl})
	}
	values(pkg.Consts)
	values(pkg.Vars)
	for _, fn := range pkg.Funcs {
		function("", fn)
	}
	for _, typ := range pkg.Types {
		declarations = append(declarations, helperDeclaration{typ.Name, typ.Doc, typ.Decl})
		values(typ.Consts)
		values(typ.Vars)
		for _, fn := range typ.Funcs {
			function("", fn)
		}
		for _, method := range typ.Methods {
			function(typ.Name+".", method)
		}
	}
	slices.SortFunc(declarations, func(a, b helperDeclaration) int { return strings.Compare(a.name, b.name) })
	return declarations
}

func helperReference(root, directory string, pkg *doc.Package) (string, error) {
	var output strings.Builder
	fmt.Fprintf(&output, "# %s\n\nGenerated by `go generate ./...`; do not edit.\n\n", directory)
	output.WriteString("Read [the routing guide](shared-helpers.md) first. ")
	if strings.HasPrefix(directory, "internal/passes/") {
		output.WriteString("This is infrastructure documentation. Analyzer summary access goes through " +
			"[the broker](summaries.md), not domain constructors or raw facts.\n\n")
	} else {
		output.WriteString("This reference lists exported contracts, not permission to bypass architecture boundaries.\n\n")
	}
	if pkg.Doc != "" {
		output.WriteString(pkg.Doc + "\n")
	}
	// A shared file set preserves physical source locations for links. go/doc's
	// filtered AST supplies signatures without bodies or unexported members.
	files := token.NewFileSet()
	parsed, err := parseHelperSource(root, directory, files)
	if err != nil {
		return "", err
	}
	for _, declaration := range helperDeclarations(parsed) {
		var signature bytes.Buffer
		if err := printer.Fprint(&signature, files, declaration.node); err != nil {
			return "", err
		}
		// Link the file, not the line: a line anchor moves with every edit
		// above the declaration and turns unrelated changes into noise in the
		// generated page's diff, while the file is stable and the name finds
		// the declaration.
		position := files.Position(declaration.node.Pos())
		path, err := filepath.Rel(root, position.Filename)
		if err != nil {
			return "", err
		}
		fmt.Fprintf(&output, "## %s\n\n[Source](../../../../%s)\n\n```go\n%s\n```\n\n",
			declaration.name, filepath.ToSlash(path), signature.String())
		if declaration.comment != "" {
			output.WriteString(declaration.comment + "\n")
		}
	}
	return strings.TrimSpace(output.String()) + "\n", nil
}

func checkHelperReferences(root string) error {
	updates := make(map[string][]byte)
	if err := generateHelperReferences(root, updates); err != nil {
		return err
	}
	for _, path := range slices.Sorted(maps.Keys(updates)) {
		current, err := os.ReadFile(path) // #nosec G304 -- paths produced by the repository reference generator
		if err != nil {
			return err
		}
		if !bytes.Equal(current, updates[path]) {
			return fmt.Errorf("%s is stale; run `go generate ./...`", path)
		}
	}
	return nil
}
